"""SSN encryption/decryption service for CRUISEAPP2.

Uses Fernet (AES-128-CBC + HMAC-SHA256) with a key derived from
an environment variable. The key must be a 32-byte base64-encoded
string generated by Fernet.generate_key().

SECURITY RULES:
- SSN is NEVER stored in plaintext in the database
- SSN is NEVER logged
- SSN is NEVER returned in any API response
- SSN is ONLY decrypted when sending to background check APIs (Checkr)
- The encryption key is NEVER hardcoded; it comes from SSN_ENCRYPTION_KEY env var
"""

import os
import logging
import re
from typing import Optional

from cryptography.fernet import Fernet, InvalidToken

logger = logging.getLogger(__name__)

# ── Key loading ──────────────────────────────────────────────────────────
_SSN_KEY_RAW = os.getenv("SSN_ENCRYPTION_KEY", "")
_fernet: Optional[Fernet] = None

if _SSN_KEY_RAW:
    try:
        _fernet = Fernet(_SSN_KEY_RAW.encode())
        logger.info("[SSN] Encryption initialized")
    except Exception as e:
        logger.error("[SSN] Invalid SSN_ENCRYPTION_KEY: %s", e)
else:
    logger.warning(
        "[SSN] SSN_ENCRYPTION_KEY not set — SSNs will be stored in plaintext. "
        "Generate a key with: python -c \"from cryptography.fernet import Fernet; "
        "print(Fernet.generate_key().decode())\""
    )


def _normalize_ssn(raw: str) -> str:
    """Strip non-digits and return 9-digit SSN or empty string."""
    digits = re.sub(r"\D", "", str(raw))
    return digits if len(digits) == 9 else ""


def encrypt_ssn(raw_ssn: str) -> str:
    """Encrypt a raw SSN and return the ciphertext as a string.

    If encryption is not configured, returns the normalized SSN
    prefixed with ``[PLAINTEXT:]`` so we can detect and migrate later.
    """
    digits = _normalize_ssn(raw_ssn)
    if not digits:
        return ""

    if _fernet is None:
        # Not configured — mark as plaintext for later migration
        return f"[PLAINTEXT:]{digits}"

    try:
        ciphertext = _fernet.encrypt(digits.encode("utf-8"))
        return ciphertext.decode("utf-8")
    except Exception as e:
        logger.error("[SSN] Encryption failed: %s", e)
        raise RuntimeError("SSN encryption failed") from e


def decrypt_ssn(ciphertext: str) -> str:
    """Decrypt a ciphertext SSN and return the raw 9-digit string.

    Handles the ``[PLAINTEXT:]`` fallback prefix for migration.
    Returns empty string if ciphertext is empty or decryption fails.
    """
    if not ciphertext:
        return ""

    # Handle plaintext fallback (migration path)
    if ciphertext.startswith("[PLAINTEXT:]"):
        return ciphertext[len("[PLAINTEXT:]"):]

    if _fernet is None:
        logger.error("[SSN] Cannot decrypt — SSN_ENCRYPTION_KEY not configured")
        return ""

    try:
        plaintext = _fernet.decrypt(ciphertext.encode("utf-8"))
        return plaintext.decode("utf-8")
    except InvalidToken:
        logger.error("[SSN] Decryption failed — invalid token (wrong key?)")
        return ""
    except Exception as e:
        logger.error("[SSN] Decryption failed: %s", e)
        return ""


def get_ssn_last4(ciphertext: str) -> Optional[str]:
    """Return the last 4 digits of an encrypted SSN WITHOUT decrypting.

    This is safe to call anywhere because it never exposes the full SSN.
    Returns None if the SSN is not valid.
    """
    # We must decrypt to get the last 4 — but we never log or return the full value
    full = decrypt_ssn(ciphertext)
    return full[-4:] if full else None


def get_ssn_masked(ciphertext: str) -> Optional[str]:
    """Return a masked SSN (***-**-XXXX) WITHOUT exposing the full value.

    Safe to return in API responses.
    """
    last4 = get_ssn_last4(ciphertext)
    return f"***-**-{last4}" if last4 else None


def is_ssn_provided(ciphertext: str) -> bool:
    """Return True if an SSN is stored (encrypted or plaintext fallback)."""
    return bool(ciphertext)


def format_ssn_for_display(raw_digits: str) -> str:
    """Format 9-digit string as XXX-XX-XXXX."""
    d = re.sub(r"\D", "", str(raw_digits))
    if len(d) == 9:
        return f"{d[:3]}-{d[3:5]}-{d[5:]}"
    return raw_digits


# ── Migration helper ─────────────────────────────────────────────────────
def migrate_plaintext_ssn(plaintext: str) -> str:
    """Encrypt a plaintext SSN for migration scripts.

    Usage in migration:
        for user in users:
            if user.ssn and not user.ssn.startswith("[PLAINTEXT:]"):
                user.ssn = migrate_plaintext_ssn(user.ssn)
    """
    return encrypt_ssn(plaintext)
